### ISSUE TITLE
separating extra modules to ecell4-*

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4-base#198]

**Comment by kaizu** [comment]
Should we prepare multiple submodules like ecell4-datasource, ecell4-microscope, ecell4-parallel, etc..? Or, is only one submodule named ecell4-extras prefered?
It think the former is better. What do you think?

**Comment by kaizu** [comment]
Once I decided to keep datasource and ensemble modules in ecell4 because these modules are lightweight and implemented purely on Python. The microscope module is planned to be integrated with scopyon (bioimaging).

**Comment by kozo2** [comment]
Pure Python part will be separated as ecell4-extras package.
We decided to return to the original policy.

**Comment by kaizu** [comment]
Migrated to https://github.com/ecell/ecell4-base/issues/322
