### ISSUE TITLE
Refactor spatiocyte world APIs

### ISSUE THREAD

**Issue by kaizu** [ecell/ecell4-base#334]

**Comment by kaizu** [comment]
https://github.com/ecell/ecell4-base/blob/master/python/lib/ecell4_base/spatiocyte.pyx

APIs:

- has_particle(ParticleID) -> bool
- get_particle(ParticleID) -> (ParticleID, Particle)
- new_particle(Particle) or new_particle(Species, Real3) -> (ParticleID, Particle)
- remove_particle(ParticleID)
- update_particle(ParticleID, Particle)
- get_voxel(ParticleID) -> ParticleVoxel or None
- get_voxel_at(Voxel) -> (ParticleID, Species)  even if it's a structure or vacant
- **Deprecated** remove_voxel(ParticleID)
- new_voxel(Species, Voxel) -> ParticleID or None
- new_voxel_structure(Species, Voxel) -> ParticleID or None (ParticleID?)
- **Deprecated** update_voxel(ParticleID, ParticleVoxel)
- **Deprecated** has_voxel(ParticleID) -> bool
- get_voxel_near_by(Real3) -> Voxel

Objects:

- Voxel
- Particle
- ParticleVoxel
- ParticleID
- Real3 (position)

**Comment by kaizu** [comment]
Okay:

- has_particle(ParticleID) -> bool
- get_particle(ParticleID) -> (ParticleID, Particle)
- new_particle(Particle) or new_particle(Species, Real3) -> (ParticleID, Particle)
- remove_particle(ParticleID)
- update_particle(ParticleID, Particle)
- **Deprecated** remove_voxel(ParticleID)
- **Deprecated** has_voxel(ParticleID) -> bool
- **Deprecated** update_voxel(ParticleID, ParticleVoxel)

Just renaming:

- get_voxel_near_by(Real3) -> Voxel => **get_voxel_nearby**
- get_voxel(ParticleID) -> ParticleVoxel or None => **get_particle_voxel** (just for debugging)
- new_voxel(Species, Voxel) -> ParticleID or None => **new_particle_at** or just **new_particle** ???

New APIs:

- get_voxel(ParticleID) -> Voxel or None
- get_particle_at(Voxel) -> (ParticleID, Particle)  How about structures?
- has_particle_at(Voxel) -> bool

Need to review:

- get_voxel_at(Voxel) -> (ParticleID, Species)  even if it's a structure or vacant
- new_voxel_structure(Species, Voxel) -> ParticleID or None (ParticleID?)

**Comment by 0ncorhynchus** [comment]
`ParticleVoxel` gives us the coordinate just for debugging, but `Voxel` can do too.
So we had better add `coordinate()` to `Voxel` and remove `ParticleVoxel`.
Due to this, we need to arrange the APIs related to them.

- [ ] Add `Voxel::coordinate() -> Integer` compiled with `DEBUG` flag
- [ ] Remove `SpatiocyteWorld::get_voxel(ParticleID) -> [ParticleVoxel | None]`

**Comment by 0ncorhynchus** [comment]
I summarize the upper plans and propose to remove APIs using `ParticleVoxel` that can be a reason for bugs.
The ToDo lists are below:

### Adding
* [ ] get_voxel(ParticleID) -> Voxel | None
* [ ] get_species_at(Voxel) -> Species
* [ ] has_particle_at(Voxel) -> bool

### Adding (for renaming)
* [ ] get_voxel_nearby(Real3) -> Voxel
* [ ] new_particle(Species, Voxel) -> ParticleID or None

### Deprecating
* [ ] remove_voxel(ParticleID)
* [ ] has_voxel(ParticleID) -> bool

### Deprecating (renamed)
* [ ] get_voxel_near_by(Real3) -> Voxel
* [ ] new_voxel(Species, Voxel) -> ParticleID | None

### Removing
* [ ] update_voxel(ParticleID, ParticleVoxel)

### Need to review
* get_voxel_at(Voxel) -> (ParticleID, Species)
* new_voxel_structure(Species, Voxel) -> ParticleID | None

About these two, it is necessary to reconsider `Structure` and `Vacant`.
