### ISSUE TITLE
Alert when a dimension mismatches

### ISSUE THREAD

**Issue by kaizu** [ecell/ecell4-base#347]
Show some warning when a dimension of the given structure mismatches the definition in the model.

```python
with species_attributes():
    A | {'location': 'M'}

m = get_model()
f = spatiocyte.Factory()
w = f.world()
w.bind_to(m)
w.add_structure(Species('M'), Sphere(ones() * 0.5, 0.4).surface())  # should alert, but nothing happens now
w.add_molecules(Species('A'), 10)

sim = f.simulator(w)  # CRASH!
```

**Comment by 0ncorhynchus** [comment]
Check List
----

- [ ] Throw an error when the dimension mismatches at `add_structure`
- [ ] Deprecate manipulating `SpatiocyteWorld` without binding `Model`
- [ ] Deprecate giving a `Species` with attributes different from `VoxelPool` to methods.
